### ISSUE TITLE
Power bar

### ISSUE THREAD

**Issue by Pival81** [phantamanta44/Tinkers-MEMES#1]
Make the tool have an actual power bar underneath it instead of just in the tooltip.

**Comment by phantamanta44** [comment]
this seems a little unlikely; forge doesn't offer any hooks for item rendering so I'd either have to use a coremod or include some bulky library that does it for me, neither of which are particularly appealing approaches

**Comment by phantamanta44** [comment]
so i bit the bullet there's a power bar coremod now; you can get the latest release [on CurseForge](https://minecraft.curseforge.com/projects/tinkers-memes)
