### ISSUE TITLE
Any way to remove hard dep on Mekanism Tools?

### ISSUE THREAD

**Issue by nephatrine** [phantamanta44/Tinkers-MEMES#10]
Is there a reason Mekanism Tools (and Generators for that matter) is a hard dependency? I would think only the base Mekanism mod is actually needed.

**Comment by phantamanta44** [comment]
I probably just added all three when I originally wrote the mod meta and never bothered to change it. Will fix later, once I'm out of class.

**Comment by nephatrine** [comment]
Wasn't expecting such a quick reply. Thanks and sorry for being a bother. I guess most people just use all three, but I usually leave Tools out myself since it doesn't really bring much to the table imo.

**Comment by phantamanta44** [comment]
patched in 1.0.7: https://www.curseforge.com/minecraft/mc-mods/tinkers-memes/files/2794143
