### ISSUE TITLE
Power bar not appearing when using Optifine

### ISSUE THREAD

**Issue by Ainsley4Ever** [phantamanta44/Tinkers-MEMES#12]
Exactly what it says in the title. When using Optifine the power bar just disappears, regardless of its charge. I tried removing Optifine, and the bar appeared again. Power consumption and modifiers work correctly, this seems to just be a visual bug. Is there a possible fix to this issue?
I'm using version 1.0.7 of your mod, Forge 1.12.2-14.23.5.2847 and Optifine 1.12.2 HD U F4.

**Comment by phantamanta44** [comment]
not sure this is fixable since optifine is extremely invasive with its rendering hacks. can you try running enderio with optifine and seeing if its energy bars appear properly?

**Comment by Ainsley4Ever** [comment]
I can confirm that EnderIO's energy bars work correctly. I used the last version of both EnderIO and EnderCore (1.12.2-0.5.72 and 1.12.2-5.1.52 respectively), and the same version of Optifine.


I also forgot to post some screenshots, so I'm doing it now.

Here are the two mods with Optifine. As you can see the energy system still works on TiC tools:
(Don't pay attention to the weird values, I messed with the configs a little bit)

![with_optifine](https://user-images.githubusercontent.com/48531562/67861395-714e6880-fb20-11e9-99c9-9344f7c71f4c.png)


And without Optifine the energy bar appears again:

![without_optifine](https://user-images.githubusercontent.com/48531562/67861411-77444980-fb20-11e9-9833-ad9f5a2fdb77.png)

**Comment by phantamanta44** [comment]
noted. will have to take a closer look later, as i am currently flooded with schoolwork.

**Comment by phantamanta44** [comment]
should be fixed in 1.0.8: https://www.curseforge.com/minecraft/mc-mods/tinkers-memes/files/2824306

**Comment by Ainsley4Ever** [comment]
Yes, it works now. Thank you for taking your time to fix this issue.
