### ISSUE TITLE
[Feature Request] Support for Construct's Armory charging

### ISSUE THREAD

**Issue by IronPiston** [phantamanta44/Tinkers-MEMES#5]

**Comment by phantamanta44** [comment]
give it a shot: https://www.curseforge.com/minecraft/mc-mods/tinkers-memes/files/2732913

**Comment by IronPiston** [comment]
Seems to work great, thanks! Question though, why are Mekanism Generators/Tools now a dependency?

**Comment by phantamanta44** [comment]
Mek gens is required for the crafting components and mek tools is required for the disassembler vein mode mechanism

**Comment by phantamanta44** [comment]
I should note that it was intended for them to be required before, but I just messed up the dependency declarations
