### ISSUE TITLE
Adding "Electromechanical Actuator" to PlusTiC's laser gun only consumes modifier but won't change how tool works

### ISSUE THREAD

**Issue by Lgmrszd** [phantamanta44/Tinkers-MEMES#6]
From description of PlusTiC mod:

> Laser Gun - an accurate ranged weapon that requires both durability and energy for attacking. It also has a mode to smelt blocks, which can be toggled by pressing Alt-Comma. If you miss, then it will not fire!

This tool has energy buffer by itself which is consumed with durability, after applying Electromechanical Actuator, the tool still has same energy buffer and still consumes with durability.

**Comment by phantamanta44** [comment]
my solution was to add an entirely new modifier for electrical tcon tools, since there isn't a great way to get around their built-in energy buffers

**Comment by Lgmrszd** [comment]
Installed & checked latest version, works perfect, thank you!
