### ISSUE TITLE
Phaser Reduces Damage Dealth on Laser  Guns

### ISSUE THREAD

**Issue by Poke5555** [phantamanta44/Tinkers-MEMES#7]
after putting the phaser on my laser gun it does significantly less damage, it still says it does 16 attack but it was one shotting vanilla mobs before i added the phaser.

**Comment by phantamanta44** [comment]
what parts and modifiers are on your gun?

**Comment by phantamanta44** [comment]
i am currently unable to replicate so i'm going to need more details

**Comment by phantamanta44** [comment]
[non issue](https://www.curseforge.com/minecraft/mc-mods/tinkers-memes?comment=11)
