### ISSUE TITLE
Disassembling Trait Crash

### ISSUE THREAD

**Issue by Zeevian** [phantamanta44/Tinkers-MEMES#9]
It seems that one of the recent updates to Mekanism broke the disassembling trait.  Now it seems that when you mine a block with the trait enabled, it causes a CTD.  Tried to mine a Silver Ore vein from thermal foundation.

[crash-2019-09-23_18.01.05-client.txt](https://github.com/phantamanta44/Tinkers-MEMES/files/3644344/crash-2019-09-23_18.01.05-client.txt)

Can't remember which update it was that started causing this. will do some more testing and figure out which update it was.  It seems to be one that was updated around mid-late June.

Using Mekanism build 9.8.1.383, Tools, and Generators.  As well as the most recent build on curseforge for Tinkers' MEMES

**Comment by Zeevian** [comment]
After testing it seems that it occur with builds 381 and later

**Comment by phantamanta44** [comment]
note: https://github.com/mekanism/Mekanism/commit/a06f2f07f468d206f9c6c3d129ba1dbc2af075ee

should be a quick 5-second fix. will get around to it later when i'm free.

**Comment by phantamanta44** [comment]
should be fixed in 1.0.6: https://www.curseforge.com/minecraft/mc-mods/tinkers-memes/files/2793696
